apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  labels:
    app: tasks-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
      - name: tasks-service
        image: tasks-service:1.0.0
        imagePullPolicy: Never # Utilise l'image locale
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgres://taskuser:taskpass@host.docker.internal:5433/taskdb"