apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
        imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.frontend }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.ports.frontend }}
